# Generated by Django 4.1.7 on 2023-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(default='', upload_to='templates/uploads'),
        ),
    ]
