# Generated by Django 4.1.7 on 2023-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_alter_mymodel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
